import { fold } from '@/lib/text'

export interface CategoryIcon {
  emoji: string
  /** What someone might type looking for it, including the words they'd use instead. */
  terms: string
}

/**
 * A chosen set, ordered by where money actually goes.
 *
 * The common answers sit in the first rows, so the usual case needs neither
 * scrolling nor searching. A full picker offers two thousand options to a
 * question with a few dozen sensible answers, and puts the one that was wanted
 * a scroll away from where it should have been.
 *
 * Every entry carries the words someone would reach for rather than the name of
 * the glyph. Nobody searches "fuel pump" for petrol — they type "gasolina", or
 * "posto", and both have to find it.
 *
 * Spending comes first, then the wider set — hearts, people, the marks that
 * stand for done and late — because a category is sometimes named after how it
 * feels rather than what it buys.
 *
 * The count is a multiple of six, so the grid never ends on a ragged row.
 */
export const CATEGORY_ICONS: CategoryIcon[] = [
  { emoji: '🏠', terms: 'casa moradia aluguel lar' },
  { emoji: '🍽️', terms: 'restaurante comida jantar almoço refeição' },
  { emoji: '🛒', terms: 'mercado supermercado compras feira' },
  { emoji: '🚗', terms: 'carro automóvel transporte' },
  { emoji: '⛽', terms: 'combustível gasolina posto etanol álcool' },
  { emoji: '💊', terms: 'farmácia remédio medicamento' },
  { emoji: '🏥', terms: 'hospital saúde médico clínica' },
  { emoji: '📚', terms: 'livros estudo leitura' },
  { emoji: '🎓', terms: 'educação faculdade escola curso mensalidade' },
  { emoji: '👕', terms: 'roupa vestuário camiseta' },
  { emoji: '✈️', terms: 'viagem avião passagem voo' },
  { emoji: '🎬', terms: 'cinema filme' },
  { emoji: '🎁', terms: 'presente lembrança' },
  { emoji: '🐶', terms: 'pet cachorro animal cão' },
  { emoji: '💡', terms: 'luz energia elétrica conta' },
  { emoji: '📱', terms: 'celular telefone plano' },
  { emoji: '💳', terms: 'cartão crédito fatura' },
  { emoji: '🏦', terms: 'banco tarifa' },
  { emoji: '💰', terms: 'dinheiro salário renda' },
  { emoji: '🔧', terms: 'manutenção conserto ferramenta' },
  { emoji: '✂️', terms: 'cabeleireiro salão corte barbeiro' },
  { emoji: '☕', terms: 'café lanche padaria' },
  { emoji: '🧾', terms: 'conta boleto imposto taxa' },
  { emoji: '🚌', terms: 'ônibus transporte público passagem' },
  { emoji: '🍕', terms: 'pizza delivery' },
  { emoji: '🍔', terms: 'hambúrguer lanche fast food' },
  { emoji: '🍺', terms: 'cerveja bar bebida' },
  { emoji: '🍷', terms: 'vinho bebida adega' },
  { emoji: '🥗', terms: 'salada saudável almoço' },
  { emoji: '🍎', terms: 'fruta feira hortifruti' },
  { emoji: '🥖', terms: 'padaria pão' },
  { emoji: '🍫', terms: 'doce chocolate sobremesa' },
  { emoji: '🚕', terms: 'táxi uber corrida aplicativo' },
  { emoji: '🚇', terms: 'metrô trem bilhete' },
  { emoji: '🚲', terms: 'bicicleta bike ciclismo' },
  { emoji: '🛵', terms: 'moto motoboy entrega' },
  { emoji: '🅿️', terms: 'estacionamento vaga' },
  { emoji: '🛣️', terms: 'pedágio estrada viagem' },
  { emoji: '🧰', terms: 'ferramentas reforma obra' },
  { emoji: '🔌', terms: 'eletrônicos eletrodoméstico energia' },
  { emoji: '💧', terms: 'água conta saneamento' },
  { emoji: '🔥', terms: 'gás botijão' },
  { emoji: '🌐', terms: 'internet wifi banda larga' },
  { emoji: '📺', terms: 'tv streaming assinatura netflix' },
  { emoji: '🎧', terms: 'música spotify fone assinatura' },
  { emoji: '🎮', terms: 'jogos games videogame' },
  { emoji: '🎵', terms: 'show música evento' },
  { emoji: '🎟️', terms: 'ingresso evento teatro' },
  { emoji: '🏋️', terms: 'academia musculação esporte' },
  { emoji: '⚽', terms: 'futebol esporte quadra' },
  { emoji: '🏖️', terms: 'praia férias lazer' },
  { emoji: '🏨', terms: 'hotel hospedagem pousada' },
  { emoji: '🧳', terms: 'mala bagagem viagem' },
  { emoji: '🗺️', terms: 'passeio turismo excursão' },
  { emoji: '📷', terms: 'foto câmera fotografia' },
  { emoji: '🎨', terms: 'arte hobby pintura' },
  { emoji: '🐱', terms: 'gato pet animal' },
  { emoji: '🦴', terms: 'ração petshop veterinário' },
  { emoji: '🌱', terms: 'planta jardim horta' },
  { emoji: '🪴', terms: 'jardinagem vaso planta' },
  { emoji: '🧹', terms: 'limpeza faxina diarista' },
  { emoji: '🧺', terms: 'lavanderia roupa lavagem' },
  { emoji: '🧴', terms: 'higiene cosmético perfume' },
  { emoji: '🧼', terms: 'sabão produto limpeza' },
  { emoji: '👟', terms: 'tênis calçado sapato' },
  { emoji: '👗', terms: 'vestido roupa moda' },
  { emoji: '💄', terms: 'maquiagem beleza' },
  { emoji: '⌚', terms: 'relógio acessório' },
  { emoji: '👶', terms: 'bebê filho criança fralda' },
  { emoji: '🎂', terms: 'aniversário festa bolo' },
  { emoji: '💐', terms: 'flores floricultura' },
  { emoji: '⛪', terms: 'igreja doação dízimo' },
  { emoji: '🎪', terms: 'lazer entretenimento parque' },
  { emoji: '🖨️', terms: 'impressão papelaria escritório' },
  { emoji: '📦', terms: 'encomenda entrega compra online' },
  { emoji: '🪙', terms: 'investimento poupança reserva' },
  { emoji: '🩺', terms: 'consulta plano de saúde exame' },
  { emoji: '🚿', terms: 'chuveiro banho casa' },
  { emoji: '❤️', terms: 'coração amor vermelho' },
  { emoji: '🧡', terms: 'coração laranja' },
  { emoji: '💛', terms: 'coração amarelo' },
  { emoji: '💚', terms: 'coração verde' },
  { emoji: '💙', terms: 'coração azul' },
  { emoji: '💜', terms: 'coração roxo' },
  { emoji: '🖤', terms: 'coração preto' },
  { emoji: '🤍', terms: 'coração branco' },
  { emoji: '💖', terms: 'coração brilhante amor' },
  { emoji: '💘', terms: 'coração flecha paixão namoro' },
  { emoji: '💔', terms: 'coração partido' },
  { emoji: '🫶', terms: 'mãos coração carinho' },
  { emoji: '👤', terms: 'pessoa perfil usuário' },
  { emoji: '👥', terms: 'pessoas grupo dupla' },
  { emoji: '👨', terms: 'homem marido' },
  { emoji: '👩', terms: 'mulher esposa' },
  { emoji: '🧑', terms: 'pessoa adulto' },
  { emoji: '👴', terms: 'idoso avô vovô' },
  { emoji: '👵', terms: 'idosa avó vovó' },
  { emoji: '🧒', terms: 'criança' },
  { emoji: '👦', terms: 'menino filho' },
  { emoji: '👧', terms: 'menina filha' },
  { emoji: '🤰', terms: 'gravidez grávida maternidade' },
  { emoji: '👨‍👩‍👧', terms: 'família casa filhos' },
  { emoji: '👨‍⚕️', terms: 'médico consulta saúde' },
  { emoji: '👩‍🏫', terms: 'professora aula escola' },
  { emoji: '👮', terms: 'polícia segurança' },
  { emoji: '🧑‍🚒', terms: 'bombeiro emergência' },
  { emoji: '👷', terms: 'obra construção pedreiro' },
  { emoji: '🧑‍🌾', terms: 'agricultor fazenda roça' },
  { emoji: '🧑‍🍳', terms: 'cozinheiro chef comida' },
  { emoji: '🧑‍💻', terms: 'trabalho freelancer computador' },
  { emoji: '🧑‍🔧', terms: 'mecânico técnico conserto' },
  { emoji: '🧑‍⚖️', terms: 'advogado justiça processo' },
  { emoji: '💇', terms: 'cabelo salão corte' },
  { emoji: '🧑‍🎨', terms: 'artista design trabalho' },
  { emoji: '🚒', terms: 'bombeiros caminhão emergência' },
  { emoji: '🚑', terms: 'ambulância emergência socorro' },
  { emoji: '🚓', terms: 'polícia viatura multa' },
  { emoji: '🧯', terms: 'extintor segurança' },
  { emoji: '⚠️', terms: 'atenção alerta aviso' },
  { emoji: '🆘', terms: 'socorro emergência urgente' },
  { emoji: '✅', terms: 'check ok feito confirmado' },
  { emoji: '❌', terms: 'errado cancelado close vermelho' },
  { emoji: '⭕', terms: 'círculo certo marcado' },
  { emoji: '❗', terms: 'importante urgente exclamação' },
  { emoji: '❓', terms: 'dúvida pergunta' },
  { emoji: '➕', terms: 'mais adicionar soma' },
  { emoji: '➖', terms: 'menos subtrair desconto' },
  { emoji: '⭐', terms: 'estrela favorito importante' },
  { emoji: '🔔', terms: 'lembrete aviso notificação' },
  { emoji: '🔒', terms: 'seguro trancado privado' },
  { emoji: '🔑', terms: 'chave acesso aluguel' },
  { emoji: '📌', terms: 'fixado importante marcador' },
  { emoji: '⏰', terms: 'relógio alarme hora prazo' },
  { emoji: '⌛', terms: 'ampulheta tempo espera' },
  { emoji: '📅', terms: 'calendário data agenda' },
  { emoji: '🗓️', terms: 'agenda mês planejamento' },
  { emoji: '🕐', terms: 'hora relógio horário' },
  { emoji: '⏳', terms: 'prazo vencimento tempo' },
  { emoji: '☀️', terms: 'sol verão dia' },
  { emoji: '🌧️', terms: 'chuva inverno guarda-chuva' },
  { emoji: '❄️', terms: 'frio neve ar condicionado' },
  { emoji: '🌡️', terms: 'temperatura febre clima' },
  { emoji: '🌈', terms: 'arco-íris diversidade' },
  { emoji: '🌙', terms: 'noite lua' },
  { emoji: '🌳', terms: 'árvore parque natureza' },
  { emoji: '🌊', terms: 'mar praia onda' },
  { emoji: '⛰️', terms: 'montanha trilha viagem' },
  { emoji: '🔆', terms: 'energia solar claridade' },
  { emoji: '🍃', terms: 'folha natureza sustentável' },
  { emoji: '🐝', terms: 'abelha mel natureza' },
  { emoji: '🛏️', terms: 'cama quarto móveis' },
  { emoji: '🛋️', terms: 'sofá sala móveis' },
  { emoji: '🚪', terms: 'porta reforma casa' },
  { emoji: '🪑', terms: 'cadeira móveis' },
  { emoji: '🖼️', terms: 'quadro decoração' },
  { emoji: '🧊', terms: 'gelo geladeira freezer' },
  { emoji: '🍳', terms: 'cozinha ovo café da manhã' },
  { emoji: '🥤', terms: 'refrigerante bebida suco' },
  { emoji: '🍦', terms: 'sorvete sobremesa' },
  { emoji: '🍿', terms: 'pipoca cinema' },
  { emoji: '🥩', terms: 'carne açougue churrasco' },
  { emoji: '🧀', terms: 'queijo frios' },
  { emoji: '💻', terms: 'notebook computador trabalho' },
  { emoji: '🖥️', terms: 'monitor computador' },
  { emoji: '⌨️', terms: 'teclado periférico' },
  { emoji: '🖱️', terms: 'mouse periférico' },
  { emoji: '📡', terms: 'antena tv sinal' },
  { emoji: '🔋', terms: 'bateria carregador energia' },
  { emoji: '📄', terms: 'documento papel contrato' },
  { emoji: '📝', terms: 'anotação nota lembrete' },
  { emoji: '📊', terms: 'relatório gráfico balanço' },
  { emoji: '📈', terms: 'alta lucro crescimento' },
  { emoji: '📉', terms: 'queda prejuízo perda' },
  { emoji: '🗂️', terms: 'arquivo pasta organização' },
  { emoji: '🎯', terms: 'meta objetivo alvo' },
  { emoji: '🧩', terms: 'quebra-cabeça hobby' },
  { emoji: '🚀', terms: 'lançamento projeto começo' },
  { emoji: '🏆', terms: 'prêmio conquista troféu' },
  { emoji: '🎉', terms: 'festa comemoração' },
  { emoji: '🙏', terms: 'agradecimento doação fé' },
]

/** Everything when the query is empty, so the grid is never a blank slate. */
export function searchIcons(query: string): CategoryIcon[] {
  const needle = fold(query.trim())

  if (needle === '') return CATEGORY_ICONS

  return CATEGORY_ICONS.filter((icon) => fold(icon.terms).includes(needle))
}
